apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: kaft-jwt
spec:
  organizationId: "a2b57f3d-6e2b-4467-b499-b31e00bfd804"
  secretName: kaft-jwt
  authToken:
    secretName: bitwarden-sec
    secretKey: token
  map:
    - bwSecretId: "409cbb50-50e8-441a-94f9-b4b20085c254"
      secretKeyName: jwtSecret
    - bwSecretId: "f6fde9e6-3666-4ce2-a5c0-b4b20085c2ee"
      secretKeyName: internalJwtSecret
---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: kaft-r2
spec:
  organizationId: "a2b57f3d-6e2b-4467-b499-b31e00bfd804"
  secretName: kaft-r2
  authToken:
    secretName: bitwarden-sec
    secretKey: token
  map:
    - bwSecretId: "9a87417e-e90e-41db-89e8-b37000ecd720"
      secretKeyName: accountId
    - bwSecretId: "eb5eb0e8-2a4a-4398-a756-b37000d87d64"
      secretKeyName: accessKeyId
    - bwSecretId: "c39086cc-e112-40eb-b19f-b37000d89090"
      secretKeyName: secretAccessKey
